# Generated by Django 4.1.2 on 2023-05-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('county_revenue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulter',
            name='address',
        ),
        migrations.RemoveField(
            model_name='defaulter',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='defaulter',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='defaulter',
            name='enterprise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='county_revenue.enterprise'),
        ),
        migrations.AddField(
            model_name='defaulter',
            name='revenue',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='county_revenue.revenue'),
        ),
        migrations.AddField(
            model_name='defaulter',
            name='service',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='county_revenue.service'),
        ),
        migrations.AlterField(
            model_name='defaulter',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
